### ISSUE TITLE
2022 editorial guidelines

### ISSUE THREAD

**Issue by Mateuszq28** [trivvz/pg-latex-template#1]
Does it meet the requirements of the 2022 editorial guidelines?

https://eti.pg.edu.pl/studenci/dyplomy

https://cdn.files.pg.edu.pl/eti/Dziekanat/regulaminy/WYTYCZNE%20%20DLA%20%20AUTOR%C3%93W%20%20PRAC%20%20I%20%20PROJEKT%C3%93W%20%20DYPLOMOWYCH%20%20na%20PG.pdf

Have you looked at other people's templates?

https://github.com/kamil95/LaTeX_PG_PDI

especially this one, because one committee even has a description that it has been checked by the Quality Management Department:
https://github.com/splaw1k/PG_LaTeX_Templates

But still, your project has the latest update commits, so I don't know which one to choose.

**Comment by tpwo** [comment]
Proponuję na polski przejść ;) Oddawałem magisterkę rok temu i na tym szablonie promotor ani nikt inny nie miał żadnych uwag. Ale myślę, że to może zależeć od konkretnych ludzi, którzy mogą mieć swoje widzimisię.

Sam się opierałem na wytycznych z 2018, bo to była najnowsza wersja, kiedy pisałem inżynierkę. I nie tworzyłem szablonu od zera, tylko dostałem jakąś wersję, która krążyła wśród studentów. Miała trochę rzeczy niezgodnych z wytycznymi i ją krok po kroku dostosowywałem. Ona bazowała też na customowej klasie dokumentu, co brzmi spoko, ale było trochę upierdliwe na dłuższą metę.

Do magisterki opierałem się na tym samym, ale zdecydowałem, że uproszczę strukturę, używając podejścia "convention over configuration". I wywaliłem definiowanie klasy dokumentu i zamiast tego obecne podejście to: sklonuj to repo i zacznij edytować pod siebie, wiedząc że masz sensowne wartości domyślne (więc raczej edytujesz ustawienia, żeby dodać nowe rzeczy, których będziesz potrzebować). Rewolucyjny commit to 5d0cb92d04d109c08887d085ccb4c4b089edc150

Jeśli kiedyś wrócę do LaTeXa to myślę, że też skorzystam z tego repo jako dobrej bazy.

Odpowiadając na pytania:

> Does it meet the requirements of the 2022 editorial guidelines?

Nie wiem, na szybko przejrzałem te wytyczne i wyglądają bardzo podobnie do tych z 2018. Zgaduję, że używanie mojego szablonu przejdzie bez problemu. Ew. z jakimiś drobnymi poprawkami przy upierdliwym promotorze (wtedy zachęcam do PRa :D)

> Have you looked at other people's templates?

https://github.com/kamil95/LaTeX_PG_PDI nie pamiętam, chyba nie znalazłem tego. https://github.com/splaw1k/PG_LaTeX_Templates na pewno widziałem i przeglądałem. Możliwe, że się nawet sugerowałem przy poprawkach do tego szablonu. On też bazuje na wytycznych z 2018, więc myślę, że jest porównywalny.

W swoim szablonie używam względnie nowych paczek, które np. mocno ułatwiają wygodne tworzenie tabel (`tabularray`) czy bibliografii (`biblatex`). Da się to robić też po staremu z tym samym efektem, ale jest mniej wygodne.

Nie chcę sugerować, który szablon wybrać, ale po napisaniu dwóch prac mam wrażenie, że zgodność z wytycznymi rektora jest dość luźno traktowana. Praca po prostu ma wyglądać estetycznie i pasować przede wszystkim Twojemu promotorowi ;-)

**Comment by Mateuszq28** [comment]
Dzięki za wskazówki! Właściwie niby są te nowe wymagania 2022, ale szablon dalej wisi stary (2018) i nawet nie napisali, co konkretnie zmienili względem poprzedniej wersji, więc chyba nie ma to takiego znaczenia...
Swoją drogą, jak się przyjrzałem, to w tym splaw1k/PG_LaTeX_Templates są źle ustawione marginesy, a u Ciebie są dobre. Pozdrawiam :)

**Comment by tpwo** [comment]
Dopisałem w 4e161ff8cbe866f6a78f4ea21607893b963764d8, że szablon jest prawdopodobnie zgodny z wytycznymi z 2022. Jakby wyszło, że są jednak jakieś różnice, to śmiało zapraszam z poprawkami!

Również pozdrawiam ;-)
